# Generated by Django 3.2.5 on 2023-03-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'db_table': 'main_news',
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'db_table': 'stock_news',
            },
        ),
    ]
