# Generated by Django 4.1.7 on 2023-03-12 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_mainsentiment"),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name="MainSentiment",
        # ),
    ]
