# Generated by Django 4.1.7 on 2023-03-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_mainsentiment"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentiment", models.IntegerField()),
                (
                    "news",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.stocknews",
                    ),
                ),
            ],
            options={
                "db_table": "stock_sentiment",
            },
        ),
    ]
