# Generated by Django 3.2.5 on 2023-03-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230310_1609'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='account',
        ),
    ]
